<script type="text/javascript"
		src="${pageContext.request.contextPath}/resources/js/bootstrap.min.js"></script>
<script type="text/javascript"
	src="${pageContext.request.contextPath}/resources/js/jquery-3.3.1.slim.min.js"></script>
<script type="text/javascript"
        src="${pageContext.request.contextPath}/resources/fusion/fusion.js"></script>
<script type="text/javascript"
        src="${pageContext.request.contextPath}/resources/js/popper.min.js"></script>
<script type="text/javascript"
		src="${pageContext.request.contextPath}/resources/js/loginForm/loginForm.js"></script>
<script type="text/javascript"
        src="${pageContext.request.contextPath}/resources/js/registrationForm/registrationForm.js"></script>